#!/bin/sh
# Ensures the book's generated sidecars exist under portal/public/data/book/
# (book-skeleton.json + extensions*), which the portal's Book viewMode serves.
#
# Generated by experiments/book-view/scripts/extractSlice.ts, whose canonical
# output is this directory; the standalone book app symlinks its public/data
# copies here, so there is exactly one copy of this data in the repo.
#
# Usage:
#   sh scripts/ensureBookData.sh          # build only if missing (dev loop)
#   sh scripts/ensureBookData.sh --force  # always rebuild
set -e

out_dir="$(cd "$(dirname "$0")/.." && pwd)/public/data/book"
skeleton="$out_dir/book-skeleton.json"
ext_dir="$out_dir/extensions"

if [ "${1:-}" != "--force" ] && [ -f "$skeleton" ] && [ -d "$ext_dir" ]; then
  exit 0
fi

echo "Building book sidecars (book-skeleton.json + extensions/*)..."
NODE_OPTIONS=--max-old-space-size=8192 npx tsx ../experiments/book-view/scripts/extractSlice.ts
