/**
 * Species Quality Analysis Script
 * Scans all family data JSON files and quantifies "name-only" / minimal species nodes.
 */
const fs = require('fs');
const path = require('path');

const ROOT = '/Users/tb/Dev/systema-naturae';

// Patterns for template-generated content
const TEMPLATE_DESC_PATTERNS = [
  /a species in the genus/i,
  /Also known as/i
];

// Auto-generated commonName = title-cased version of the species epithet
// e.g. name: "Eutropis allapallensis" → commonName: "Eutropis Allapallensis"
function isAutoGeneratedCommonName(speciesName, commonName) {
  if (!commonName || !speciesName) return false;
  // Split scientific name: "Genus epithet" → ["Genus", "epithet"]
  const parts = speciesName.trim().split(/\s+/);
  if (parts.length < 2) return false;
  const genus = parts[0];
  const epithet = parts.slice(1).join(' ');
  // Auto-generated: commonName matches "Genus Epithet" (title-cased)
  const expectedAuto = genus + ' ' + epithet.replace(/\b\w/g, c => c.toUpperCase());
  return commonName === expectedAuto;
}

function isTemplateDescription(desc) {
  if (!desc) return false;
  return TEMPLATE_DESC_PATTERNS.some(p => p.test(desc));
}

function isEmptyContinents(continents) {
  return !continents || !Array.isArray(continents) || continents.length === 0;
}

function hasRealCommonName(node) {
  if (!node.commonName) return false;
  return !isAutoGeneratedCommonName(node.name, node.commonName);
}

function hasRealDescription(node) {
  if (!node.description) return false;
  return !isTemplateDescription(node.description);
}

function isBare(node) {
  // Bare = no commonName, no description, no continents, no lineage, no subspeciesCount
  const hasCn = !!node.commonName;
  const hasDesc = !!node.description;
  const hasCont = !!node.continents && Array.isArray(node.continents) && node.continents.length > 0;
  const hasLin = !!node.lineage;
  const hasSs = node.subspeciesCount !== undefined && node.subspeciesCount !== null;
  // If it only has name + rank + id (+ maybe lineage which is common even in bare ones)
  const usefulFields = [hasCn, hasDesc, hasCont, hasLin, hasSs].filter(Boolean).length;
  return usefulFields <= 1; // only has lineage at most
}

function isFullyPopulated(node) {
  return (
    hasRealCommonName(node) &&
    hasRealDescription(node) &&
    !isEmptyContinents(node.continents) &&
    node.subspeciesCount !== undefined &&
    node.subspeciesCount !== null
  );
}

function isMinimal(node) {
  // Minimal = bare OR (auto-generated commonName AND no real commonName) OR template description
  if (isBare(node)) return true;
  if (node.hasCommonName && !node.realCommonName) return true;
  if (node.templateDescription) return true;
  return false;
}

function walkTree(node, familyName, familyPath, results) {
  if (node.rank === 'SPECIES' || node.rank === 'SUBSPECIES') {
    const entry = {
      familyName,
      familyPath,
      id: node.id || '',
      name: node.name || '',
      rank: node.rank,
      hasCommonName: !!node.commonName,
      realCommonName: hasRealCommonName(node),
      hasLineage: !!node.lineage,
      hasContinents: !isEmptyContinents(node.continents),
      continentsCount: node.continents ? node.continents.length : 0,
      hasSubspeciesCount: node.subspeciesCount !== undefined && node.subspeciesCount !== null,
      subspeciesCount: node.subspeciesCount,
      hasDescription: !!node.description,
      templateDescription: isTemplateDescription(node.description),
      realDescription: hasRealDescription(node),
      hasSourcedFrom: !!node.sourcedFrom,
      sourcedFrom: node.sourcedFrom || '',
      isBare: false,
      isFullyPopulated: false,
      category: ''
    };

    entry.isBare = isBare(node);
    entry.isMinimal = entry.isBare || (entry.hasCommonName && !entry.realCommonName) || entry.templateDescription;

    // Determine category
    if (entry.isBare) {
      entry.category = 'BARE';
    } else if (isFullyPopulated(node)) {
      entry.isFullyPopulated = true;
      entry.category = 'FULL';
    } else if (hasRealCommonName(node) && hasRealDescription(node)) {
      entry.category = 'GOOD';
    } else if (hasRealCommonName(node) && !hasRealDescription(node)) {
      entry.category = 'PARTIAL_NODESC';
    } else if (!hasRealCommonName(node) && hasRealDescription(node)) {
      entry.category = 'PARTIAL_NOCOMMON';
    } else if (entry.templateDescription && !hasRealCommonName(node)) {
      entry.category = 'TEMPLATE';
    } else {
      entry.category = 'MINIMAL';
    }

    results.species.push(entry);
    results.totalSpecies++;
    return;
  }

  if (node.children && Array.isArray(node.children)) {
    for (const child of node.children) {
      walkTree(child, familyName, familyPath, results);
    }
  }
}

function analyzeFile(filePath) {
  const relPath = path.relative(ROOT, filePath);
  const familyName = path.basename(filePath, '.json');
  const results = { species: [], totalSpecies: 0 };

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const data = JSON.parse(content);

    if (data.rank === 'FAMILY' && data.children) {
      for (const child of data.children) {
        walkTree(child, familyName, relPath, results);
      }
    }
  } catch (err) {
    console.error(`  ERROR reading ${relPath}: ${err.message}`);
  }

  return results;
}

function main() {
  const dataFiles = [];
  findDataFiles(ROOT, dataFiles);
  console.log(`Found ${dataFiles.length} data files to scan.\n`);

  const allResults = [];
  let grandTotalSpecies = 0;

  for (const filePath of dataFiles) {
    const result = analyzeFile(filePath);
    if (result.totalSpecies > 0) {
      allResults.push({
        familyName: path.basename(filePath, '.json'),
        familyPath: path.relative(ROOT, filePath),
        ...summarize(result)
      });
      grandTotalSpecies += result.totalSpecies;
    }
  }

  // Sort by total species descending for the report
  allResults.sort((a, b) => b.totalSpecies - a.totalSpecies);

  // Aggregates
  let totalSpecies = 0;
  let totalBare = 0;
  let totalTemplate = 0;
  let totalNoDesc = 0;
  let totalNoCommon = 0;
  let totalNoContinents = 0;
  let totalNoLineage = 0;
  let totalFullyPopulated = 0;
  let totalAutoCommon = 0;
  let totalNoSubspeciesCount = 0;
  let totalMinimal = 0;

  for (const r of allResults) {
    totalSpecies += r.totalSpecies;
    totalBare += r.bare;
    totalTemplate += r.template;
    totalNoDesc += r.noDescription;
    totalNoCommon += r.noRealCommonName;
    totalNoContinents += r.noContinents;
    totalNoLineage += r.noLineage;
    totalFullyPopulated += r.fullyPopulated;
    totalAutoCommon += r.autoCommonName;
    totalNoSubspeciesCount += r.noSubspeciesCount;
    totalMinimal += r.minimal;
  }

  // Build report
  const lines = [];
  lines.push('='.repeat(90));
  lines.push('  SYSTEMA NATURAE — SPECIES NODE QUALITY ANALYSIS');
  lines.push('='.repeat(90));
  lines.push('');
  lines.push(`Total data files scanned: ${allResults.length}`);
  lines.push(`Total species nodes:      ${totalSpecies.toLocaleString()}`);
  lines.push('');
  lines.push('─'.repeat(90));
  lines.push('  GLOBAL SUMMARY');
  lines.push('─'.repeat(90));
  lines.push('');

  lines.push(`  Truly bare (only name + rank ± id):                    ${totalBare.toLocaleString()}  (${(totalBare / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  Auto-generated commonName (title-cased scientific):    ${totalAutoCommon.toLocaleString()}  (${(totalAutoCommon / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  Template-generated description:                        ${totalTemplate.toLocaleString()}  (${(totalTemplate / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  No real description at all:                            ${totalNoDesc.toLocaleString()}  (${(totalNoDesc / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  No real commonName:                                    ${totalNoCommon.toLocaleString()}  (${(totalNoCommon / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  No continent data:                                     ${totalNoContinents.toLocaleString()}  (${(totalNoContinents / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  No lineage:                                            ${totalNoLineage.toLocaleString()}  (${(totalNoLineage / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  No subspeciesCount:                                    ${totalNoSubspeciesCount.toLocaleString()}  (${(totalNoSubspeciesCount / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  FULLY POPULATED (real CN + real desc + continents):    ${totalFullyPopulated.toLocaleString()}  (${(totalFullyPopulated / totalSpecies * 100).toFixed(1)}%)`);
  lines.push(`  MINIMAL/NODE-ONLY (bare + auto CN + template):        ${totalMinimal.toLocaleString()}  (${(totalMinimal / totalSpecies * 100).toFixed(1)}%)`);
  lines.push('');

  // Families with highest proportion of bare nodes
  lines.push('─'.repeat(90));
  lines.push('  TOP 20 FAMILIES — HIGHEST BARE/MINIMAL PROPORTION');
  lines.push('─'.repeat(90));
  lines.push('');

  const byMinPct = [...allResults].sort((a, b) => b.minimal / b.totalSpecies - a.minimal / a.totalSpecies);
  lines.push(`${'RANK'.padStart(4)} ${'FAMILY'.padEnd(30)} ${'TOTAL'.padStart(8)} ${'MINIMAL'.padStart(8)} ${'MIN%'.padStart(7)}`);
  lines.push(''.padEnd(60, '─'));
  byMinPct.slice(0, 20).forEach((r, i) => {
    const pct = (r.minimal / r.totalSpecies * 100).toFixed(1);
    lines.push(`${(i + 1).toString().padStart(4)} ${r.familyName.padEnd(30)} ${r.totalSpecies.toString().padStart(8)} ${r.minimal.toString().padStart(8)} ${(pct + '%').padStart(7)}`);
  });
  lines.push('');

  // Families with highest proportion of fully populated nodes
  lines.push('─'.repeat(90));
  lines.push('  TOP 10 FAMILIES — HIGHEST FULLY-POPULATED PROPORTION');
  lines.push('─'.repeat(90));
  lines.push('');

  const byFullPct = [...allResults].sort((a, b) => b.fullyPopulated / b.totalSpecies - a.fullyPopulated / a.totalSpecies).filter(r => r.fullyPopulated > 0);
  lines.push(`${'RANK'.padStart(4)} ${'FAMILY'.padEnd(30)} ${'TOTAL'.padStart(8)} ${'FULL'.padStart(7)} ${'FULL%'.padStart(7)}`);
  lines.push(''.padEnd(56, '─'));
  byFullPct.slice(0, 10).forEach((r, i) => {
    const pct = (r.fullyPopulated / r.totalSpecies * 100).toFixed(1);
    lines.push(`${(i + 1).toString().padStart(4)} ${r.familyName.padEnd(30)} ${r.totalSpecies.toString().padStart(8)} ${r.fullyPopulated.toString().padStart(7)} ${(pct + '%').padStart(7)}`);
  });
  lines.push('');

  // Families with most species
  lines.push('─'.repeat(90));
  lines.push('  TOP 20 FAMILIES — LARGEST (MOST SPECIES NODES)');
  lines.push('─'.repeat(90));
  lines.push('');

  lines.push(`${'RANK'.padStart(4)} ${'FAMILY'.padEnd(30)} ${'TOTAL'.padStart(8)} ${'BARE'.padStart(6)} ${'TMPL'.padStart(6)} ${'AUTO-CN'.padStart(8)} ${'FULL'.padStart(7)} ${'MIN%'.padStart(7)}`);
  lines.push(''.padEnd(76, '─'));
  allResults.slice(0, 20).forEach((r, i) => {
    const pct = (r.minimal / r.totalSpecies * 100).toFixed(1);
    lines.push(`${(i + 1).toString().padStart(4)} ${r.familyName.padEnd(30)} ${r.totalSpecies.toString().padStart(8)} ${r.bare.toString().padStart(6)} ${r.template.toString().padStart(6)} ${r.autoCommonName.toString().padStart(8)} ${r.fullyPopulated.toString().padStart(7)} ${(pct + '%').padStart(7)}`);
  });
  lines.push('');

  // Full per-family breakdown
  lines.push('='.repeat(90));
  lines.push('  PER-FAMILY BREAKDOWN (ALL FAMILIES)');
  lines.push('='.repeat(90));
  lines.push('');
  lines.push(`${'FAMILY'.padEnd(32)} ${'TOTAL'.padStart(6)} ${'BARE'.padStart(5)} ${'TMPL'.padStart(5)} ${'AUTOCN'.padStart(6)} ${'NODESC'.padStart(6)} ${'NOCC'.padStart(5)} ${'FULL'.padStart(5)} ${'MIN%'.padStart(6)}`);
  lines.push(''.padEnd(80, '─'));

  for (const r of allResults) {
    const pct = (r.minimal / r.totalSpecies * 100).toFixed(1);
    lines.push(`${r.familyName.padEnd(32)} ${r.totalSpecies.toString().padStart(6)} ${r.bare.toString().padStart(5)} ${r.template.toString().padStart(5)} ${r.autoCommonName.toString().padStart(6)} ${r.noDescription.toString().padStart(6)} ${r.noContinents.toString().padStart(5)} ${r.fullyPopulated.toString().padStart(5)} ${(pct + '%').padStart(6)}`);
  }

  lines.push('');
  lines.push('─'.repeat(90));
  lines.push('  LEGEND');
  lines.push('─'.repeat(90));
  lines.push('  BARE    = only name + rank (+ maybe id) — no other useful fields');
  lines.push('  TMPL    = has template-generated description ("a species in the genus..." / "Also known as")');
  lines.push('  AUTOCN  = commonName is auto-generated title-case of scientific name (e.g. "Eutropis Allapallensis")');
  lines.push('  NODESC  = species with no description field at all (not even template)');
  lines.push('  NOCC    = no continent data (continents missing or empty array)');
  lines.push('  FULL    = has real commonName + real description + continent data + subspeciesCount');
  lines.push('  MIN%    = minimal (unique species that are bare OR auto-CN OR template) / TOTAL');
  lines.push('');

  // Count by category
  const cats = {};
  for (const r of allResults) {
    for (const c of ['bare', 'template', 'autoCommonName', 'noDescription', 'noRealCommonName', 'noContinents', 'noLineage', 'fullyPopulated', 'noSubspeciesCount']) {
      cats[c] = (cats[c] || 0) + r[c];
    }
  }

  return lines.join('\n');
}

function findDataFiles(dir, results) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!entry.name.startsWith('.') && entry.name !== 'node_modules') {
        findDataFiles(fullPath, results);
      }
    } else if (entry.name.endsWith('.json') && fullPath.includes('/src/data/') && entry.name !== 'continents.json') {
      results.push(fullPath);
    }
  }
}

function summarize(result) {
  const bare = result.species.filter(s => s.isBare).length;
  const template = result.species.filter(s => s.templateDescription).length;
  const noDescription = result.species.filter(s => !s.hasDescription).length;
  const noRealCommonName = result.species.filter(s => !s.realCommonName).length;
  const autoCommonName = result.species.filter(s => s.hasCommonName && !s.realCommonName).length;
  const noContinents = result.species.filter(s => !s.hasContinents).length;
  const noLineage = result.species.filter(s => !s.hasLineage).length;
  const fullyPopulated = result.species.filter(s => s.isFullyPopulated).length;
  const noSubspeciesCount = result.species.filter(s => !s.hasSubspeciesCount).length;
  const minimal = result.species.filter(s => s.isMinimal).length;

  return {
    totalSpecies: result.totalSpecies,
    bare,
    template,
    noDescription,
    noRealCommonName,
    autoCommonName,
    noContinents,
    noLineage,
    fullyPopulated,
    noSubspeciesCount,
    minimal
  };
}

const report = main();
console.log(report);
fs.writeFileSync('/tmp/species-analysis.txt', report);
console.log('\nReport saved to /tmp/species-analysis.txt');
