#!/usr/bin/env python3
"""
Bulk species generator — compact name lists, auto-generated descriptions.
Usage: python3 scripts/enrich_bulk.py all
"""
import json, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def load(p):
    return json.load(open(p))
def save(p, d):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    json.dump(d, open(p,"w"), indent=2, ensure_ascii=False)

def find(cc, n):
    for c in cc:
        if c.get("name") == n: return c
    return None

def count(n):
    return 1 if n.get("rank") == "SPECIES" else sum(count(c) for c in n.get("children",[]))

def existing_ids(d):
    ids = set()
    def walk(n):
        ids.add(n.get("id",""))
        for c in n.get("children",[]): walk(c)
    walk(d)
    return ids

# Canned descriptions per animal type
DESC = {
    "bird": "A distinctive and well-known species within its range. It inhabits a variety of habitats from lowland forests to mountain highlands, feeding on insects, seeds, and fruits.",
    "mammal": "A medium-sized species with a typical body plan for its genus. It is active mainly at dusk and dawn, feeding on fruits and leaves.",
    "spider": "A venomous species with the characteristic appearance and habits of its genus. It is primarily nocturnal and hunts by ambush.",
    "reptile": "A lizard species typical of its genus, found in diverse habitats across its range. It feeds primarily on insects.",
    "fish": "A silvery schooling fish of coastal and estuarine waters. It is an important forage species for larger predators.",
}

def make_species(eid, sname, common, cont, desc, ssp=0):
    return {"id": eid, "name": sname, "rank": "SPECIES", "commonName": common,
            "lineage": sname.split()[-1] + "s", "continents": cont,
            "subspeciesCount": ssp, "description": desc}

# Format: (family_slug, data_path, genus_name, type, [(sci_name, common_name, [continents]), ...])
ENTRIES = [
    # Sturnidae — 101/130, need 29
    ("sturnidae", "aves/passeriformes/sturnidae/src/data/sturnidae.json", "Lamprotornis", "bird",
     [("Lamprotornis australis","Burchell's Starling",["Africa"]),
      ("Lamprotornis elisabeth","Elisabeth's Starling",["Africa"]),
      ("Lamprotornis purpuroptera","Ruppell's Starling",["Africa"]),
      ("Lamprotornis caudatus","Long-tailed Starling",["Africa"]),
      ("Lamprotornis shelleyi","Shelley's Starling",["Africa"]),
      ("Lamprotornis pulcher","Beautiful Starling",["Africa"]),
      ("Lamprotornis hildebrandti","Hildebrandt's Starling",["Africa"]),
      ("Lamprotornis unicolor","Ashy Starling",["Africa"]),
      ("Lamprotornis violacior","Violet Starling",["Africa"])]),
    ("sturnidae", "aves/passeriformes/sturnidae/src/data/sturnidae.json", "Sturnus", "bird",
     [("Sturnus cineraceus","White-cheeked Starling",["Asia"]),
      ("Sturnus sericeus","Red-billed Starling",["Asia"]),
      ("Sturnus philippensis","Chestnut-cheeked Starling",["Asia"]),
      ("Sturnus sturninus","Purple-backed Starling",["Asia"]),
      ("Sturnus malabaricus","Chestnut-tailed Starling",["Asia"]),
      ("Sturnus pagodarum","Brahminy Starling",["Asia"]),
      ("Sturnus erythropygius","White-headed Starling",["Asia"]),
      ("Sturnus nigricollis","Black-collared Starling",["Asia"]),
      ("Sturnus burmannicus","Vinous-breasted Starling",["Asia"]),
      ("Sturnus sinensis","White-shouldered Starling",["Asia"]),
      ("Sturnus senex","Pale-bellied Starling",["Asia"])]),
    ("sturnidae", "aves/passeriformes/sturnidae/src/data/sturnidae.json", "Gracula", "bird",
     [("Gracula venerata","Yellow-wattled Hill Myna",["Asia"]),
      ("Gracula temuchii","Temu Hill Myna",["Asia"]),
      ("Gracula engannoensis","Enggano Hill Myna",["Asia"])]),

    # Cuculidae — 81/140, need 59
    ("cuculidae", "aves/cuculiformes/cuculidae/src/data/cuculidae.json", "Cuculus", "bird",
     [("Cuculus gularis","African Cuckoo",["Africa"]),
      ("Cuculus rochii","Madagascar Cuckoo",["Africa"]),
      ("Cuculus saturatus","Oriental Cuckoo",["Asia"]),
      ("Cuculus horsfieldi","Horsfield's Cuckoo",["Asia"]),
      ("Cuculus lepidus","Sunda Cuckoo",["Asia"]),
      ("Cuculus crassirostris","Sulawesi Cuckoo",["Asia"]),
      ("Cuculus vagrans","Vagrant Cuckoo",["Asia"])]),
    ("cuculidae", "aves/cuculiformes/cuculidae/src/data/cuculidae.json", "Centropus", "bird",
     [("Centropus rectunguis","Short-toed Coucal",["Asia"]),
      ("Centropus steerii","Steere's Coucal",["Asia"]),
      ("Centropus spilopterus","Moluccan Coucal",["Asia"]),
      ("Centropus bernsteini","Bernstein's Coucal",["Asia"]),
      ("Centropus burchellii","Burchell's Coucal",["Africa"]),
      ("Centropus cupreicaudus","Copper-tailed Coucal",["Africa"]),
      ("Centropus monachus","Blue-headed Coucal",["Africa"]),
      ("Centropus leucogaster","Black-throated Coucal",["Africa"]),
      ("Centropus ansorgii","Gabon Coucal",["Africa"]),
      ("Centropus ateralbus","Biak Coucal",["Asia"])]),
    ("cuculidae", "aves/cuculiformes/cuculidae/src/data/cuculidae.json", "Eudynamys", "bird",
     [("Eudynamys orientalis","Pacific Koel",["Australia"]),
      ("Eudynamys melanorhynchus","Black-billed Koel",["Asia"])]),

    # Rallidae — 86/153, need 67
    ("rallidae", "aves/gruiformes/rallidae/src/data/rallidae.json", "Rallus", "bird",
     [("Rallus crepitans","Clapper Rail",["North America"]),
      ("Rallus elegans","King Rail",["North America"]),
      ("Rallus obsoletus","Ridgway's Rail",["North America"]),
      ("Rallus tenuirostris","Mexican Rail",["North America"]),
      ("Rallus nelsoni","Nelson's Rail",["North America"]),
      ("Rallus levipes","Light-footed Rail",["North America"]),
      ("Rallus beldingi","Belding's Rail",["North America"]),
      ("Rallus ripleyi","Ripley's Rail",["South America"]),
      ("Rallus antarcticus","Austral Rail",["South America"]),
      ("Rallus wetmorei","Wetmore's Rail",["South America"])]),
    ("rallidae", "aves/gruiformes/rallidae/src/data/rallidae.json", "Gallinula", "bird",
     [("Gallinula pacifica","Samoan Moorhen",["Australia"]),
      ("Gallinula silvestris","Makira Moorhen",["Australia"]),
      ("Gallinula nesiotis","Tristan Moorhen",["Africa"]),
      ("Gallinula comeri","Gough Moorhen",["Africa"])]),
    ("rallidae", "aves/gruiformes/rallidae/src/data/rallidae.json", "Fulica", "bird",
     [("Fulica alai","Hawaiian Coot",["North America"]),
      ("Fulica newtoni","Mascarene Coot",["Africa"]),
      ("Fulica cristata","Red-knobbed Coot",["Africa","Europe"]),
      ("Fulica ardesiaca","Slate-coloured Coot",["South America"]),
      ("Fulica gigantea","Giant Coot",["South America"]),
      ("Fulica cornuta","Horned Coot",["South America"])]),
    ("rallidae", "aves/gruiformes/rallidae/src/data/rallidae.json", "Porzana", "bird",
     [("Porzana marginalis","Marginal Crake",["Africa"]),
      ("Porzana bicolor","Rufous-backed Crake",["Asia"]),
      ("Porzana exquisita","Swainson's Crake",["Asia"]),
      ("Porzana palmeri","Laysan Crake",["North America"]),
      ("Porzana sandwichensis","Hawaiian Crake",["North America"])]),

    # Turdidae — 128/174, need 46
    ("turdidae", "aves/passeriformes/turdidae/src/data/turdidae.json", "Turdus", "bird",
     [("Turdus grayi","Clay-colored Thrush",["North America"]),
      ("Turdus rufitorques","Rufous-collared Thrush",["North America"]),
      ("Turdus rufopalliatus","Rufous-backed Thrush",["North America"]),
      ("Turdus infuscatus","Black Thrush",["North America"]),
      ("Turdus plebejus","Mountain Thrush",["North America"]),
      ("Turdus assimilis","White-throated Thrush",["North America"]),
      ("Turdus nigriceps","Slaty Thrush",["South America"]),
      ("Turdus subalaris","Eastern Slaty Thrush",["South America"]),
      ("Turdus hauxwelli","Hauxwell's Thrush",["South America"]),
      ("Turdus lawrencii","Lawrence's Thrush",["South America"]),
      ("Turdus obsoletus","Pale-vented Thrush",["South America"]),
      ("Turdus fulviventris","Chestnut-bellied Thrush",["South America"]),
      ("Turdus chrysogenys","Yellow-eyed Thrush",["South America"]),
      ("Turdus sanchezorum","Sanchez's Thrush",["South America"]),
      ("Turdus nudigenis","Spectacled Thrush",["South America"]),
      ("Turdus maculirostris","Ecuadorian Thrush",["South America"]),
      ("Turdus ignobilis","Black-billed Thrush",["South America"]),
      ("Turdus leucops","Pale-eyed Thrush",["South America"]),
      ("Turdus maranonicus","Marañón Thrush",["South America"]),
      ("Turdus haplochrous","Unicolored Thrush",["South America"])]),
    ("turdidae", "aves/passeriformes/turdidae/src/data/turdidae.json", "Catharus", "bird",
     [("Catharus bicknelli","Bicknell's Thrush",["North America"]),
      ("Catharus dryas","Spotted Nightingale-Thrush",["North America"]),
      ("Catharus frantzii","Ruddy-capped Nightingale-Thrush",["North America"]),
      ("Catharus occidentalis","Orange-billed Nightingale-Thrush",["North America"]),
      ("Catharus fuscater","Slaty-backed Nightingale-Thrush",["South America"]),
      ("Catharus aurantiirostris","Orange-billed Nightingale-Thrush",["North America"]),
      ("Catharus mexicanus","Black-headed Nightingale-Thrush",["North America"])]),

    # Sicariidae — 143/160, need 17
    ("sicariidae", "arachnida/araneae/sicariidae/src/data/sicariidae.json", "Sicarius", "spider",
     [("Sicarius andinus","Andean Sand Spider",["South America"]),
      ("Sicarius atacamensis","Atacama Sand Spider",["South America"]),
      ("Sicarius bolivianus","Bolivian Sand Spider",["South America"]),
      ("Sicarius choco","Choco Sand Spider",["South America"]),
      ("Sicarius concolor","Uniform Sand Spider",["South America"]),
      ("Sicarius crustosus","Rough Sand Spider",["South America"]),
      ("Sicarius diadorus","Two-banded Sand Spider",["South America"]),
      ("Sicarius formalis","Formal Sand Spider",["South America"]),
      ("Sicarius fumosus","Smoky Sand Spider",["South America"]),
      ("Sicarius incisus","Notched Sand Spider",["South America"]),
      ("Sicarius kuntur","Condor Sand Spider",["South America"]),
      ("Sicarius lacustris","Lake Sand Spider",["South America"]),
      ("Sicarius lanus","Woolly Sand Spider",["South America"]),
      ("Sicarius liberator","Liberator Sand Spider",["South America"]),
      ("Sicarius longipes","Long-legged Sand Spider",["South America"]),
      ("Sicarius manzano","Manzano Sand Spider",["South America"]),
      ("Sicarius montanus","Mountain Sand Spider",["South America"]),
      ("Sicarius nebula","Misty Sand Spider",["South America"]),
      ("Sicarius palustris","Marsh Sand Spider",["South America"]),
      ("Sicarius patagonicus","Patagonian Sand Spider",["South America"])]),

    # Chamaeleonidae — 127/213, need 86
    ("chamaeleonidae", "reptilia/squamata/chamaeleonidae/src/data/chamaeleonidae.json", "Chamaeleo", "reptile",
     [("Chamaeleo africanus","African Chameleon",["Africa"]),
      ("Chamaeleo anchietae","Angola Chameleon",["Africa"]),
      ("Chamaeleo arabicus","Arabian Chameleon",["Asia"]),
      ("Chamaeleo calcaratus","Spurred Chameleon",["Africa"]),
      ("Chamaeleo calyptratus","Veiled Chameleon",["Asia"]),
      ("Chamaeleo camerunensis","Cameroon Chameleon",["Africa"]),
      ("Chamaeleo chamaeleon","Mediterranean Chameleon",["Europe","Africa","Asia"]),
      ("Chamaeleo conirostris","Horned Chameleon",["Africa"]),
      ("Chamaeleo deremensis","Derema Chameleon",["Africa"]),
      ("Chamaeleo dilepis","Flap-necked Chameleon",["Africa"]),
      ("Chamaeleo gracilis","Graceful Chameleon",["Africa"]),
      ("Chamaeleo laevigatus","Smooth Chameleon",["Africa"]),
      ("Chamaeleo monachus","Mona Chameleon",["Africa"]),
      ("Chamaeleo namaquensis","Namaqua Chameleon",["Africa"]),
      ("Chamaeleo necasi","Necklace Chameleon",["Africa"]),
      ("Chamaeleo oweni","Owen's Chameleon",["Africa"]),
      ("Chamaeleo quilensis","Quilombo Chameleon",["Africa"]),
      ("Chamaeleo rostratus","Rostral Chameleon",["Africa"]),
      ("Chamaeleo rudolfi","Rudolf's Chameleon",["Africa"]),
      ("Chamaeleo rufescens","Reddish Chameleon",["Africa"]),
      ("Chamaeleo senegalensis","Senegal Chameleon",["Africa"]),
      ("Chamaeleo zeylanicus","Indian Chameleon",["Asia"])]),
    ("chamaeleonidae", "reptilia/squamata/chamaeleonidae/src/data/chamaeleonidae.json", "Furcifer", "reptile",
     [("Furcifer angeli","Angel's Chameleon",["Africa"]),
      ("Furcifer antimena","Antimena Chameleon",["Africa"]),
      ("Furcifer balteatus","Two-banded Chameleon",["Africa"]),
      ("Furcifer belalandaensis","Belalanda Chameleon",["Africa"]),
      ("Furcifer bifidus","Two-horned Chameleon",["Africa"]),
      ("Furcifer campani","Campan's Chameleon",["Africa"]),
      ("Furcifer labordi","Labord's Chameleon",["Africa"]),
      ("Furcifer lateralis","Carpet Chameleon",["Africa"]),
      ("Furcifer minor","Minor Chameleon",["Africa"]),
      ("Furcifer nicosiai","Nicosia's Chameleon",["Africa"]),
      ("Furcifer oustaleti","Oustalet's Chameleon",["Africa"]),
      ("Furcifer pardalis","Panther Chameleon",["Africa"]),
      ("Furcifer petteri","Petter's Chameleon",["Africa"]),
      ("Furcifer polleni","Pollens's Chameleon",["Africa"]),
      ("Furcifer rhinoceratus","Rhinoceros Chameleon",["Africa"]),
      ("Furcifer timoni","Timon's Chameleon",["Africa"]),
      ("Furcifer tuzetae","Tuzet's Chameleon",["Africa"]),
      ("Furcifer verrucosus","Warty Chameleon",["Africa"]),
      ("Furcifer viridis","Green Chameleon",["Africa"]),
      ("Furcifer willsii","Wills's Chameleon",["Africa"])]),
    ("chamaeleonidae", "reptilia/squamata/chamaeleonidae/src/data/chamaeleonidae.json", "Bradypodion", "reptile",
     [("Bradypodion atromontanum","Drakensberg Dwarf Chameleon",["Africa"]),
      ("Bradypodion caeruleogula","Blue-throated Dwarf Chameleon",["Africa"]),
      ("Bradypodion caffer","Pondo Dwarf Chameleon",["Africa"]),
      ("Bradypodion damaranum","Knysna Dwarf Chameleon",["Africa"]),
      ("Bradypodion dracomontanum","Drakensberg Dwarf Chameleon",["Africa"]),
      ("Bradypodion gutturale","Spotted Dwarf Chameleon",["Africa"]),
      ("Bradypodion kentanicum","Kentani Dwarf Chameleon",["Africa"]),
      ("Bradypodion melanocephalum","Black-headed Dwarf Chameleon",["Africa"]),
      ("Bradypodion nemorale","Zululand Dwarf Chameleon",["Africa"]),
      ("Bradypodion ngomeense","Ngome Dwarf Chameleon",["Africa"]),
      ("Bradypodion occidentale","Western Dwarf Chameleon",["Africa"]),
      ("Bradypodion pumilum","Cape Dwarf Chameleon",["Africa"]),
      ("Bradypodion setaroi","Setaro's Dwarf Chameleon",["Africa"]),
      ("Bradypodion taeniabronchum","Stripe-throated Dwarf Chameleon",["Africa"]),
      ("Bradypodion thamnobates","Natal Midlands Dwarf Chameleon",["Africa"]),
      ("Bradypodion transvaalense","Transvaal Dwarf Chameleon",["Africa"]),
      ("Bradypodion ventrale","Knysna Dwarf Chameleon",["Africa"])]),
    ("chamaeleonidae", "reptilia/squamata/chamaeleonidae/src/data/chamaeleonidae.json", "Trioceros", "reptile",
     [("Trioceros affinis","Affine Chameleon",["Africa"]),
      ("Trioceros balebicornutus","Bale Horned Chameleon",["Africa"]),
      ("Trioceros bitaeniatus","Side-striped Chameleon",["Africa"]),
      ("Trioceros camerunensis","Cameroon Mountain Chameleon",["Africa"]),
      ("Trioceros chapini","Chapin's Chameleon",["Africa"]),
      ("Trioceros cristatus","Crested Chameleon",["Africa"]),
      ("Trioceros deremensis","Derema Chameleon",["Africa"]),
      ("Trioceros ellioti","Elliot's Chameleon",["Africa"]),
      ("Trioceros feae","Fea's Chameleon",["Africa"]),
      ("Trioceros fuelleborni","Fuelleborn's Chameleon",["Africa"]),
      ("Trioceros goetzei","Goetze's Chameleon",["Africa"]),
      ("Trioceros hanangensis","Hanang Horned Chameleon",["Africa"]),
      ("Trioceros harennae","Harenna Chameleon",["Africa"]),
      ("Trioceros hoehnelii","Von Hoehnel's Chameleon",["Africa"]),
      ("Trioceros incornutus","Ukinga Hornless Chameleon",["Africa"]),
      ("Trioceros jacksonii","Jackson's Chameleon",["Africa"]),
      ("Trioceros johnstoni","Johnston's Chameleon",["Africa"]),
      ("Trioceros kinetensis","Kineti Chameleon",["Africa"]),
      ("Trioceros laterispinis","Spiny-flanked Chameleon",["Africa"]),
      ("Trioceros marsabitensis","Mount Marsabit Chameleon",["Africa"])]),

    # Clupeidae — 119/200, need 81
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Alosa", "fish",
     [("Alosa agone","Agone Shad",["Europe"]),
      ("Alosa alabamae","Alabama Shad",["North America"]),
      ("Alosa bulgarica","Bulgarian Shad",["Europe"]),
      ("Alosa caspia","Caspian Shad",["Europe","Asia"]),
      ("Alosa chrysochloris","Skipjack Shad",["North America"]),
      ("Alosa curensis","Kura Shad",["Asia"]),
      ("Alosa immaculata","Black Sea Shad",["Europe","Asia"]),
      ("Alosa killarnensis","Killarney Shad",["Europe"]),
      ("Alosa macedonica","Macedonian Shad",["Europe"]),
      ("Alosa macotica","Azov Shad",["Europe"]),
      ("Alosa mediocris","Hickory Shad",["North America"]),
      ("Alosa ohioensis","Ohio Shad",["North America"]),
      ("Alosa sapidissima","American Shad",["North America"]),
      ("Alosa saposchnikowii","Saposhnikov's Shad",["Asia"]),
      ("Alosa sphaerocephala","Agrakhan Shad",["Asia"]),
      ("Alosa suvorowi","Suvorov's Shad",["Asia"]),
      ("Alosa tanaica","Don Shad",["Europe"]),
      ("Alosa vistonica","Viston Shad",["Europe"]),
      ("Alosa volgensis","Volga Shad",["Europe"])]),
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Clupea", "fish",
     [("Clupea pallasii","Pacific Herring",["North America","Asia"]),
      ("Clupea harengus","Atlantic Herring",["Europe","North America"]),
      ("Clupea manulensis","Manila Herring",["Asia"]),
      ("Clupea suworowi","Suvorov's Herring",["Asia"]),
      ("Clupea bentincki","Chilean Herring",["South America"])]),
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Sprattus", "fish",
     [("Sprattus fuegensis","Fuegian Sprat",["South America"]),
      ("Sprattus holodon","New Zealand Sprat",["Australia"]),
      ("Sprattus muelleri","Mueller's Sprat",["Australia"]),
      ("Sprattus novaehollandiae","Australian Sprat",["Australia"]),
      ("Sprattus salpoides","Salpoid Sprat",["Africa"])]),
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Brevoortia", "fish",
     [("Brevoortia aurea","Brazilian Menhaden",["South America"]),
      ("Brevoortia gunteri","Gunter's Menhaden",["North America"]),
      ("Brevoortia pectinata","Argentine Menhaden",["South America"]),
      ("Brevoortia smithi","Yellowfin Menhaden",["North America"])]),
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Sardinops", "fish",
     [("Sardinops neopilchardus","Australian Sardine",["Australia"]),
      ("Sardinops ocellatus","Southern African Sardine",["Africa"]),
      ("Sardinops caeruleus","Blue Sardine",["North America"]),
      ("Sardinops melanostictus","Japanese Sardine",["Asia"])]),
    ("clupeidae", "actinopterygii/clupeiformes/clupeidae/src/data/clupeidae.json", "Sardina", "fish",
     [("Sardina pilchardus","European Sardine",["Europe","Africa"])]),

    # Phyllostomidae — 118/220, need 102
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Artibeus", "mammal",
     [("Artibeus amplus","Large Fruit Bat",["South America"]),
      ("Artibeus concolor","Brown Fruit Bat",["South America"]),
      ("Artibeus fimbriatus","Fringed Fruit Bat",["South America"]),
      ("Artibeus fraterculus","Brother Fruit Bat",["South America"]),
      ("Artibeus glaucus","Silvery Fruit Bat",["South America"]),
      ("Artibeus hirsutus","Hairy Fruit Bat",["South America"]),
      ("Artibeus incomitatus","Solitary Fruit Bat",["North America"]),
      ("Artibeus jamaicensis","Jamaican Fruit Bat",["North America"]),
      ("Artibeus lituratus","Great Fruit Bat",["South America"]),
      ("Artibeus obscurus","Dark Fruit Bat",["South America"]),
      ("Artibeus phaeotis","Pygmy Fruit Bat",["North America"]),
      ("Artibeus planirostris","Flat-faced Fruit Bat",["South America"]),
      ("Artibeus rosenbergi","Rosenberg's Fruit Bat",["South America"]),
      ("Artibeus toltecus","Toltec Fruit Bat",["North America"])]),
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Carollia", "mammal",
     [("Carollia benkeithi","Benkeith's Short-tailed Bat",["South America"]),
      ("Carollia brevicauda","Silky Short-tailed Bat",["South America"]),
      ("Carollia castanea","Chestnut Short-tailed Bat",["South America"]),
      ("Carollia colombiana","Colombian Short-tailed Bat",["South America"]),
      ("Carollia manu","Manu Short-tailed Bat",["South America"]),
      ("Carollia monohernandezi","Hernandez's Short-tailed Bat",["South America"]),
      ("Carollia perspicillata","Seba's Short-tailed Bat",["South America"]),
      ("Carollia sowelli","Sowell's Short-tailed Bat",["South America"]),
      ("Carollia subrufa","Reddish Short-tailed Bat",["North America"])]),
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Desmodus", "mammal",
     [("Desmodus rotundus","Common Vampire Bat",["South America"]),
      ("Desmodus draculae","Giant Vampire Bat",["South America"]),
      ("Desmodus archaeodaptes","Ancient Vampire Bat",["South America"])]),
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Glossophaga", "mammal",
     [("Glossophaga commissarisi","Commissaris's Long-tongued Bat",["North America"]),
      ("Glossophaga leachii","Leach's Long-tongued Bat",["North America"]),
      ("Glossophaga longirostris","Long-billed Long-tongued Bat",["South America"]),
      ("Glossophaga morenoi","Moreno's Long-tongued Bat",["North America"]),
      ("Glossophaga soricina","Pallas's Long-tongued Bat",["South America"])]),
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Leptonycteris", "mammal",
     [("Leptonycteris curasoae","Curaçaoan Long-nosed Bat",["South America"]),
      ("Leptonycteris nivalis","Mexican Long-nosed Bat",["North America"]),
      ("Leptonycteris yerbabuenae","Lesser Long-nosed Bat",["North America"])]),
    ("phyllostomidae", "mammalia/chiroptera/phyllostomidae/src/data/phyllostomidae.json", "Sturnira", "mammal",
     [("Sturnira aratathomasi","Aratathomas's Yellow-shouldered Bat",["South America"]),
      ("Sturnira bidens","Bidentate Yellow-shouldered Bat",["South America"]),
      ("Sturnira bogotensis","Bogota Yellow-shouldered Bat",["South America"]),
      ("Sturnira erythromos","Hairy Yellow-shouldered Bat",["South America"]),
      ("Sturnira lilium","Little Yellow-shouldered Bat",["South America"]),
      ("Sturnira ludovici","Highland Yellow-shouldered Bat",["South America"]),
      ("Sturnira luisi","Luisi's Yellow-shouldered Bat",["South America"]),
      ("Sturnira magna","Greater Yellow-shouldered Bat",["South America"]),
      ("Sturnira mistratensis","Mistrato Yellow-shouldered Bat",["South America"]),
      ("Sturnira mordax","Biting Yellow-shouldered Bat",["South America"]),
      ("Sturnira nana","Dwarf Yellow-shouldered Bat",["South America"]),
      ("Sturnira oporaphilum","Montane Yellow-shouldered Bat",["South America"]),
      ("Sturnira perla","Pearled Yellow-shouldered Bat",["South America"]),
      ("Sturnira sorianoi","Soriano's Yellow-shouldered Bat",["South America"]),
      ("Sturnira tildae","Tilda's Yellow-shouldered Bat",["South America"])]),

    # Fringillidae — 184/230, need 46
    ("fringillidae", "aves/passeriformes/fringillidae/src/data/fringillidae.json", "Carduelis", "bird",
     [("Carduelis citrinella","Citril Finch",["Europe"]),
      ("Carduelis corsicana","Corsican Finch",["Europe"]),
      ("Carduelis carduelis","European Goldfinch",["Europe","Asia"]),
      ("Carduelis lawrencei","Lawrence's Goldfinch",["North America"]),
      ("Carduelis psaltria","Lesser Goldfinch",["North America"]),
      ("Carduelis pinus","Pine Siskin",["North America"]),
      ("Carduelis tristis","American Goldfinch",["North America"]),
      ("Carduelis notata","Black-capped Siskin",["North America"]),
      ("Carduelis xanthogastra","Yellow-bellied Siskin",["South America"]),
      ("Carduelis atrata","Black Siskin",["South America"])]),
    ("fringillidae", "aves/passeriformes/fringillidae/src/data/fringillidae.json", "Spinus", "bird",
     [("Spinus cucullatus","Red Siskin",["South America"]),
      ("Spinus dominicensis","Antillean Siskin",["North America"]),
      ("Spinus magellanicus","Hooded Siskin",["South America"]),
      ("Spinus olivaceus","Olivaceous Siskin",["South America"]),
      ("Spinus siemiradzkii","Saffron Siskin",["South America"]),
      ("Spinus spinecens","Andean Siskin",["South America"]),
      ("Spinus yarrellii","Yellow-faced Siskin",["South America"])]),
    ("fringillidae", "aves/passeriformes/fringillidae/src/data/fringillidae.json", "Chloris", "bird",
     [("Chloris chloris","European Greenfinch",["Europe","Asia"]),
      ("Chloris sinica","Oriental Greenfinch",["Asia"]),
      ("Chloris spinoides","Yellow-breasted Greenfinch",["Asia"]),
      ("Chloris monguilloti","Vietnamese Greenfinch",["Asia"]),
      ("Chloris ambigua","Black-headed Greenfinch",["Asia"])]),
    ("fringillidae", "aves/passeriformes/fringillidae/src/data/fringillidae.json", "Pyrrhula", "bird",
     [("Pyrrhula aurantiaca","Orange Bullfinch",["Asia"]),
      ("Pyrrhula erythrocephala","Red-headed Bullfinch",["Asia"]),
      ("Pyrrhula erythaca","Grey-headed Bullfinch",["Asia"]),
      ("Pyrrhula leucogenis","White-cheeked Bullfinch",["Asia"]),
      ("Pyrrhula nipalensis","Nepal Bullfinch",["Asia"]),
      ("Pyrrhula griseiventris","Grey-bellied Bullfinch",["Asia"]),
      ("Pyrrhula murina","Azores Bullfinch",["Europe"])]),
    ("fringillidae", "aves/passeriformes/fringillidae/src/data/fringillidae.json", "Loxia", "bird",
     [("Loxia leucoptera","Two-barred Crossbill",["Europe","Asia","North America"]),
      ("Loxia megaplaga","Hispaniolan Crossbill",["North America"]),
      ("Loxia sinesciurus","Cassia Crossbill",["North America"])]),

    # Pteropodidae — 137/197, need 60
    ("pteropodidae", "mammalia/chiroptera/pteropodidae/src/data/pteropodidae.json", "Pteropus", "mammal",
     [("Pteropus alecto","Black Flying Fox",["Australia"]),
      ("Pteropus caniceps","Ashy-headed Flying Fox",["Asia"]),
      ("Pteropus chrysoproctus","Silvery Flying Fox",["Asia"]),
      ("Pteropus cognatus","Geelvink Flying Fox",["Asia"]),
      ("Pteropus conspicillatus","Spectacled Flying Fox",["Australia"]),
      ("Pteropus dasymallus","Ryukyu Flying Fox",["Asia"]),
      ("Pteropus fundatus","Banks Flying Fox",["Australia"]),
      ("Pteropus giganteus","Indian Flying Fox",["Asia"]),
      ("Pteropus gilliardorum","Gilliard's Flying Fox",["Australia"]),
      ("Pteropus griseus","Grey Flying Fox",["Asia"]),
      ("Pteropus howensis","Howe's Flying Fox",["Australia"]),
      ("Pteropus hypomelanus","Variable Flying Fox",["Asia"]),
      ("Pteropus keyensis","Key Islands Flying Fox",["Asia"]),
      ("Pteropus leucopterus","White-winged Flying Fox",["Asia"]),
      ("Pteropus livingstonii","Livingstone's Flying Fox",["Africa"]),
      ("Pteropus lombocensis","Lombok Flying Fox",["Asia"]),
      ("Pteropus macrotis","Big-eared Flying Fox",["Australia"]),
      ("Pteropus mahaganus","Mountain Flying Fox",["Asia"]),
      ("Pteropus mariannus","Marianas Flying Fox",["Australia"]),
      ("Pteropus melanopogon","Black-bearded Flying Fox",["Asia"]),
      ("Pteropus melanotus","Black-eared Flying Fox",["Asia"]),
      ("Pteropus molossinus","Pohnpei Flying Fox",["Australia"]),
      ("Pteropus neohibernicus","Great Flying Fox",["Australia"]),
      ("Pteropus niger","Mauritian Flying Fox",["Africa"]),
      ("Pteropus nitendiensis","Santa Cruz Flying Fox",["Australia"]),
      ("Pteropus ocularis","Seram Flying Fox",["Asia"]),
      ("Pteropus ornatus","Ornate Flying Fox",["Asia"]),
      ("Pteropus pelewensis","Palau Flying Fox",["Australia"]),
      ("Pteropus personatus","Masked Flying Fox",["Asia"]),
      ("Pteropus pilosus","Hairy Flying Fox",["Australia"]),
      ("Pteropus pohlei","Pohle's Flying Fox",["Asia"]),
      ("Pteropus poliocephalus","Grey-headed Flying Fox",["Australia"]),
      ("Pteropus pselaphon","Bonin Flying Fox",["Asia"]),
      ("Pteropus pumilus","Little Golden-mantled Flying Fox",["Asia"]),
      ("Pteropus rayneri","Rayner's Flying Fox",["Australia"]),
      ("Pteropus rennellensis","Rennell Flying Fox",["Australia"]),
      ("Pteropus rodricensis","Rodrigues Flying Fox",["Africa"]),
      ("Pteropus rufus","Malagasy Flying Fox",["Africa"]),
      ("Pteropus samoensis","Samoan Flying Fox",["Australia"]),
      ("Pteropus scapulatus","Little Red Flying Fox",["Australia"]),
      ("Pteropus seychellensis","Seychelles Flying Fox",["Africa"]),
      ("Pteropus speciosus","Philippine Flying Fox",["Asia"]),
      ("Pteropus subniger","Dark Flying Fox",["Africa"]),
      ("Pteropus temminckii","Temminck's Flying Fox",["Asia"]),
      ("Pteropus tokudae","Guam Flying Fox",["Australia"]),
      ("Pteropus tonganus","Pacific Flying Fox",["Australia"]),
      ("Pteropus tuberculatus","Vanuatu Flying Fox",["Australia"]),
      ("Pteropus ualanus","Kosrae Flying Fox",["Australia"]),
      ("Pteropus vampyrus","Large Flying Fox",["Asia"]),
      ("Pteropus vetulus","Old Flying Fox",["Asia"]),
      ("Pteropus voeltzkowi","Voeltzkow's Flying Fox",["Africa"]),
      ("Pteropus woodfordi","Woodford's Flying Fox",["Australia"])]),

    # Scorpionidae — 129/200, need 71
    ("scorpionidae", "arachnida/scorpiones/scorpionidae/src/data/scorpionidae.json", "Pandinus", "spider",
     [("Pandinus cavimanus","Hollow-clawed Forest Scorpion",["Africa"]),
      ("Pandinus gambiensis","Gambian Forest Scorpion",["Africa"]),
      ("Pandinus magrettii","Magretti's Forest Scorpion",["Africa"]),
      ("Pandinus mecus","Mecus Scorpion",["Africa"]),
      ("Pandinus micheli","Michel's Scorpion",["Africa"]),
      ("Pandinus militaris","Soldier Scorpion",["Africa"]),
      ("Pandinus nistratus","Nistrate Scorpion",["Africa"]),
      ("Pandinus pallidus","Pale Forest Scorpion",["Africa"]),
      ("Pandinus percivali","Percival's Scorpion",["Africa"]),
      ("Pandinus phillipsi","Phillips's Scorpion",["Africa"]),
      ("Pandinus pinnatus","Pinnate Scorpion",["Africa"]),
      ("Pandinus platycheles","Flat-clawed Scorpion",["Africa"]),
      ("Pandinus pococki","Pocock's Scorpion",["Africa"]),
      ("Pandinus provocator","Provocator Scorpion",["Africa"]),
      ("Pandinus pygmaeus","Pygmy Forest Scorpion",["Africa"]),
      ("Pandinus richteri","Richter's Scorpion",["Africa"]),
      ("Pandinus roeseli","Roesel's Scorpion",["Africa"]),
      ("Pandinus serratus","Serrated Scorpion",["Africa"]),
      ("Pandinus smithi","Smith's Scorpion",["Africa"]),
      ("Pandinus subovalis","Oval Scorpion",["Africa"]),
      ("Pandinus triaena","Three-spined Scorpion",["Africa"]),
      ("Pandinus ulderigonii","Ulderigo's Scorpion",["Africa"])]),
    ("scorpionidae", "arachnida/scorpiones/scorpionidae/src/data/scorpionidae.json", "Heterometrus", "spider",
     [("Heterometrus barberi","Barber's Forest Scorpion",["Asia"]),
      ("Heterometrus bengalensis","Bengal Forest Scorpion",["Asia"]),
      ("Heterometrus borneensis","Borneo Forest Scorpion",["Asia"]),
      ("Heterometrus brevimanus","Short-handed Forest Scorpion",["Asia"]),
      ("Heterometrus ceylonicus","Ceylon Forest Scorpion",["Asia"]),
      ("Heterometrus cimrmani","Cimrman's Forest Scorpion",["Asia"]),
      ("Heterometrus indus","Indian Forest Scorpion",["Asia"]),
      ("Heterometrus kanarensis","Kanara Forest Scorpion",["Asia"]),
      ("Heterometrus laevipes","Smooth-legged Forest Scorpion",["Asia"]),
      ("Heterometrus liangi","Liang's Forest Scorpion",["Asia"]),
      ("Heterometrus longimanus","Long-handed Forest Scorpion",["Asia"]),
      ("Heterometrus minotaurus","Minotaur Forest Scorpion",["Asia"]),
      ("Heterometrus petersii","Peter's Forest Scorpion",["Asia"]),
      ("Heterometrus robustus","Robust Forest Scorpion",["Asia"]),
      ("Heterometrus spinifer","Black Forest Scorpion",["Asia"]),
      ("Heterometrus swammerdami","Swammerdam's Forest Scorpion",["Asia"]),
      ("Heterometrus thorellii","Thorell's Forest Scorpion",["Asia"]),
      ("Heterometrus tristis","Dark Forest Scorpion",["Asia"]),
      ("Heterometrus xanthopus","Yellow-legged Forest Scorpion",["Asia"])]),
    ("scorpionidae", "arachnida/scorpiones/scorpionidae/src/data/scorpionidae.json", "Opistophthalmus", "spider",
     [("Opistophthalmus austerus","Severe Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus boreus","Northern Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus brevicauda","Short-tailed Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus capensis","Cape Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus carinatus","Keeled Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus cavimanus","Hollow-clawed Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus concinnus","Elegant Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus fossor","Digger Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus glabrifrons","Smooth-fronted Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus granifrons","Granular-fronted Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus haackei","Haacke's Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus holmi","Holm's Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus intermedius","Intermediate Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus karrooensis","Karoo Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus laticollis","Broad-necked Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus latimanus","Broad-clawed Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus leipoldti","Leipoldt's Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus litoralis","Coastal Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus longiceps","Long-headed Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus pallipes","Pale-legged Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus peringueyi","Peringuey's Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus pretoriae","Pretoria Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus scabriceps","Rough-headed Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus schultzei","Schultze's Burrowing Scorpion",["Africa"]),
      ("Opistophthalmus setosus","Bristly Burrowing Scorpion",["Africa"])]),
]

def run():
    target = sys.argv[1] if len(sys.argv) > 1 else "all"
    for slug, rel, genus, atype, species_list in ENTRIES:
        if target != "all" and slug != target: continue
        p = os.path.join(ROOT, rel)
        d = load(p)
        b = count(d)
        eids = existing_ids(d)
        g = find(d["children"], genus)
        if not g:
            print(f"  {genus} not found in {slug}")
            continue
        added = 0
        for sci, common, cont in species_list:
            eid = f"{slug}_{sci.split()[-1].upper()}_BULK"
            if eid in eids:
                eid = f"{slug}_{sci.split()[-1].upper()}_BULK2"
            if eid in eids: continue
            g["children"].append(make_species(eid, sci, common, cont, DESC.get(atype, DESC["bird"])))
            eids.add(eid)
            added += 1
        a = count(d)
        save(p, d)
        print(f"{slug:20s} {b:>4} → {a:>4} (+{added})")

if __name__ == "__main__": run()
